# -*- coding: utf-8 -*-
"""Coursehero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o4y_IlqZm-nfkT5am-jpey2TZhYGphRO

## a) **Matplotlib** is an amazing visualization library in Python for 2D plots of arrays. Matplotlib is a multi-platform data visualization library built on NumPy arrays and designed to work with the broader SciPy stack
"""

import matplotlib.pyplot as plt

# Data to plot
labels = 'Python', 'C++', 'Ruby', 'Java'
sizes = [215, 130, 245, 210]
colors = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue']
explode = (0.1, 0, 0, 0)  # explode 1st slice

# Plot
plt.pie(sizes, explode=explode, labels=labels, colors=colors,
autopct='%1.1f%%', shadow=True, startangle=140)

plt.axis('equal')
plt.show()

"""## b) **yfinance** is not affiliated, endorsed, or vetted by Yahoo, Inc. It's an open-source tool that uses Yahoo's publicly available APIs, and is intended for research and educational purposes.

API stands for “Application Programming Interface.” An API is a software intermediary that allows two applications to talk to each other. In other words, an API is the messenger that delivers your request to the provider that you're requesting it from and then delivers the response back to you.

Installing yfinance
"""

!pip install yfinance

import yfinance as yf

stock_list = ['0005.HK', '0006.HK', '0066.HK', '0700.HK', '2800.HK']
print('stock_list:', stock_list)
data = yf.download(stock_list, start="2015-01-01", end="2020-02-21")
print('data fields downloaded:', set(data.columns.get_level_values(0)))
data.head()

set(data.columns.get_level_values(0))

# Get specific columns
print('Volume data:')
data['Volume'].head()

"""## c) **SciPy** in Python is an open-source library used for solving mathematical, scientific, engineering, and technical problems. It allows users to manipulate the data and visualize the data using a wide range of high-level Python commands."""

import numpy as np  
from scipy import interpolate  
import matplotlib.pyplot as plt

x = np.linspace(0, 5, 10)  
y = np.cos(x**2/3+4) 
plt.scatter(x,y,c='r')  
plt.show()

